// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrownnffrqscquutynsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yb3dubmZmcnFzY3F1dXR5bnNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNTc0MjEsImV4cCI6MjA3MDczMzQyMX0.Xjn3F2yW1wanDf4o8M0G_9Y6DAROZL-1M14n4WuMe9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});